services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/ideanest  # Change 'mydatabase' to your actual DB name
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"